version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend_container
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./users.db
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend
    container_name: frontend_container
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - BASE_URL=http://backend:8000
